# Generated by Django 5.2.8 on 2025-12-14 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kor', models.CharField(blank=True, default='', max_length=100, verbose_name='지원자')),
                ('name_eng', models.CharField(blank=True, default='', max_length=100, verbose_name='영문이름')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별')),
                ('nationality', models.CharField(blank=True, default='', max_length=100, verbose_name='국적')),
                ('postal_code', models.CharField(blank=True, default='', max_length=10, verbose_name='우편번호')),
                ('address1', models.CharField(blank=True, default='', max_length=200, verbose_name='주소1')),
                ('address2', models.CharField(blank=True, default='', max_length=200, verbose_name='주소2')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='전화번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
