# Generated by Django 5.2.8 on 2025-12-14 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPortfolio',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='career_portfolio', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data', models.JSONField(default=dict, help_text='AI 서버에서 생성한 포트폴리오 전체 JSON')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'career_portfolios',
            },
        ),
        migrations.CreateModel(
            name='CareerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='첫 메시지 요약 or 나중에 유저가 붙일 세션 이름', max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', '진행중'), ('closed', '종료')], default='active', max_length=10)),
                ('ready_for_recommend', models.BooleanField(default=False, help_text='AI 추천(포트폴리오 생성)까지 완료되었는지 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'career_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', '사용자'), ('assistant', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='career.careersession')),
            ],
            options={
                'db_table': 'career_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
