# Generated by Django 5.2.8 on 2025-12-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0004_coverletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerportfolio",
            name="ready_for_recommend",
            field=models.BooleanField(
                default=False,
                help_text="추천 가능 상태인지 (AI control.ready_for_recommend를 저장)",
            ),
        ),
        migrations.AddField(
            model_name="careerportfolio",
            name="recommend_hint",
            field=models.TextField(
                blank=True,
                help_text="AI control.recommend_hint (정보 부족 시 안내)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="careerportfolio",
            name="stage",
            field=models.CharField(
                blank=True,
                help_text="AI control.stage (ex: collecting_info / ready_for_recommend)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="careerportfolio",
            name="data",
            field=models.JSONField(
                default=dict,
                help_text="AI 서버에서 생성/업데이트한 포트폴리오 전체 JSON",
            ),
        ),
        migrations.AlterField(
            model_name="careersession",
            name="ready_for_recommend",
            field=models.BooleanField(
                default=False,
                help_text="(권장: deprecated) 추천 준비 여부는 CareerPortfolio에 두는 게 일관됨",
            ),
        ),
    ]
