# Generated by Django 5.2.8 on 2025-12-17 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_careerportfolio_ready_for_recommend_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('DONE', '완료'), ('FAILED', '실패')], default='PENDING', max_length=10)),
                ('snapshot', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('template', models.CharField(default='default', max_length=50)),
                ('language', models.CharField(default='ko', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experience_docs',
                'ordering': ['-created_at'],
            },
        ),
    ]
